### ISSUE TITLE
Document: How to Expose Objects

### ISSUE THREAD

**Issue by BobGneu** [OpenGneu/Flathead#4]
> As a Flathead User I need a document explaining how to use it to expose an object to the JS land so I can manipulate it and send signals back to C++ land.
### Acceptance Criteria
- Unit Tests in place demonstrating exposing objects
- Document added to the Wiki for review & tracking
- Document proof read and signed off by two technical reviewers

**Comment by BobGneu** [comment]
Unit Tests available here: https://github.com/OpenGneu/Flathead/blob/master/test/Flathead/Fixtures/Types/ObjectTests.cpp
How To Expose Objects: https://github.com/OpenGneu/Flathead/wiki/Exposing-Instances-of-C---Objects

**Comment by Dn2** [comment]
Pretty clear and easy to follow. 
This feels like a nitpick but under the "Exposing Functions" header seems like you meant "across platforms" instead of "across platform". Don't hate me :D 

Thanks for the write up!

**Comment by BobGneu** [comment]
Thanks duder!

Noted and updated.
